[strategy]
name = "StgBDSXv5"
project = "srp"
strategy_id = "StgBDSXv5"

[params]
"策略" = "BDSXv5"
"近月代碼" = "TXF (台指期)"
"契約價值" = "200"
"最小跳動點" = "1"
"貨幣" = "NTD"
"開始日期" = "2025-01-01"
"結束日期" = "2026-12-31"
"滑價" = "0.02%"

[params."策略參數"]
"策略名稱" = "BDSXv5"
"多進場比" = "1%"
"空進場比" = "91%"
"空進場與多同" = "False"
"最少進場點" = "0"
"最多進場次數" = "5"
"停損後加碼" = "False"
"最多進場口數" = "1"
"最多口數絕對值" = "False"
"自動停止天數" = "0"
"進場價格修正" = "True"
"跳空處理" = "無"
"可當沖" = "True"
"總停利" = "10000"
"停損比" = "0.5%"
"停止分鐘" = "0"
"夜盤模式" = "與日盤相同"
"夜停損計算" = "相對日收盤價"
"夜盤停損" = "300"
"夜盤停利" = "500"
"加碼模式" = "無"
"有加碼" = "False"
"星期加碼" = "False"
"價差加碼" = "False"
"下單基數2" = "10"
"下單基數" = "1"
"星期一乘數" = "1"
"星期二乘數" = "1"
"星期三乘數" = "1"
"星期四乘數" = "1"
"星期五乘數" = "1"
"價差模式" = "日價差30"
"正價差點數" = "10"
"逆價差點數" = "20"
"正價差作多乘數" = "0"
"正價差作空乘數" = "2"
"逆價差作多乘數" = "2026-01-02"
"逆價差作空乘數" = "0"
"進場模式" = "每日"
"每n分" = "60"
"畫線分鐘偏移" = "0"
"結算前n日" = "15"
"漲跌n點" = "100"
"BD線開盤時間" = "900"
"BD線最後時間" = "1344"
"BD線週N劃線" = "1"
"BD線月N劃線" = "1"
"BD線濾網點" = "0"
"結算日動作" = "換倉"
"每日收盤動作" = "留倉"
"留倉最多口數" = "1000"
"平倉時間" = "1344"
"年假留倉" = "留倉"
"年假天數" = "7"
"Version" = "v26.04.01.36888"
"策略版本" = "v17.08.10"
"策略商品" = "TXF (台指期)"
"最小升降單位" = "1"
"滑價xTick" = "0.02%"
"KBAR間隔ex" = "1"
"KBAR間隔" = "1"
"KBAR啟始值" = "1"
"報價偏移" = "0"
"開始交易時間" = "845"
"最後交易時間" = "1345"
"開始日期" = "2025-01-01"
"結束日期" = "2026-12-31"
"隱藏複合界面" = "False"
"ATR長度" = "100"
"部位管理" = "固定一口"
"固定金額" = "10000"
"金額乘數" = "1"
"最小口數" = "1"
"啟動移停比" = "1%"
"移停拉回比" = "1%"
"移停增量比" = "0"
"直接停利比" = "4%"
"直停限價" = "False"
"累計績效" = "276680.2400"
"MaxDrawdown" = "-711800.9600"
"交易次數" = "212"
"交易口數" = "106"
"交易點數" = "2803997"
"GrossProfit" = "3429055.1200"
"GrossLoss" = "-3152374.8800"
"ProfitFactor" = "1.0877688252610362127996655017"
"ProfitOverDrawdown" = "0.3887045052594478096798295973"
"ProfitOverCount" = "2610.1909433962264150943396226"

