[strategy]
name = "StgBDSXv5"
project = "srp"
strategy_id = "StgBDSXv5"

[params]
"策略" = "BDSXv5"
"近月代碼" = "BTC (Bitcoin)"
"滑價" = "0.02%"
"交易時間" = "00:00-23:59"
"契約價值" = "1"
"最小跳動點" = "0.01"
"最小跳動金額" = "0.01"
"開始日期" = "2026/01/01"
"結束日期" = "2026/12/31"
"隱藏複合界面" = "1"

[params."策略參數"]
"Version" = "v26.04.01.27183"
"滑價xTick" = "0.02%"
"KBAR間隔ex" = "1/4"
"報價偏移" = "0"
"開始交易時間" = "0"
"最後交易時間" = "2359"
"開始日期" = "2026/01/01"
"結束日期" = "2026/12/31"
"ATR長度" = "100"
"部位管理" = "固定金額"
"固定金額" = "10000"
"交易金額檔案" = ""
"金額乘數" = "1"
"最小口數" = "1"
"啟動移停比" = "3%"
"移停拉回比" = "2%"
"移停增量比" = "0"
"直接停利比" = "10%"
"直停限價" = "false"
"累計績效" = "46.364609904000000"
"MaxDrawdown" = "-642.326718536000000"
"交易次數" = "68"
"交易口數" = "4555"
"交易點數" = "338064.62524000000"
"GrossProfit" = "2516.577304284000000"
"GrossLoss" = "-2470.212694380000000"
"回測商品" = "-"
"多進場比" = "1%"
"空進場比" = "1%"
"空進場與多同" = "true"
"最少進場點" = "0"
"最多進場次數" = "5"
"停損後加碼" = "false"
"最多進場口數" = "1"
"最多口數絕對值" = "false"
"自動停止天數" = "0"
"進場價格修正" = "true"
"跳空處理" = "無"
"可當沖" = "true"
"總停利" = "10000"
"停損比" = "1%"
"停止分鐘" = "0"
"夜盤模式" = "與日盤相同"
"夜停損計算" = "相對日收盤價"
"夜盤停損" = "300"
"夜盤停利" = "500"
"加碼模式" = "無"
"下單基數2" = "1"
"星期一乘數" = "1"
"星期二乘數" = "1"
"星期三乘數" = "1"
"星期四乘數" = "1"
"星期五乘數" = "1"
"價差模式" = "日價差30"
"正價差點數" = "10"
"逆價差點數" = "20"
"正價差作多乘數" = "0"
"正價差作空乘數" = "2"
"逆價差作多乘數" = "1.2"
"逆價差作空乘數" = "0"
"進場模式" = "每週"
"每n分" = "60"
"畫線分鐘偏移" = "0"
"結算前n日" = "15"
"漲跌n點" = "100"
"BD線開盤時間" = "0"
"BD線最後時間" = "1344"
"BD線週N劃線" = "1"
"BD線月N劃線" = "1"
"BD線濾網點" = "0"
"結算日動作" = "換倉"
"每日收盤動作" = "留倉"
"留倉最多口數" = "1000"
"平倉時間" = "1344"
"年假留倉" = "留倉"
"年假天數" = "7"
