[strategy]
name = "fd05_BDS"
project = "srp"
strategy_id = "fd05_BDS"

[params]
"策略" = "fd05_BDS"
"近月代碼" = "SI (Silver)"
"滑價" = "0.005"
"交易時間" = "09:30-13:24"
"契約價值" = "5000"
"最小跳動點" = "0.005"
"最小跳動金額" = "25"
"開始日期" = "2014/08/28"
"結束日期" = "2026/01/22"

[params."策略參數"]
"fee" = "1"
"startDate" = "2004-07-01"
"停損" = "2%"
"出場參數沿用原價" = "否"
"分線高低差濾網" = "無"
"分線高低差長度" = "14"
"劃線日曆日" = "0"
"劃線星期" = "1"
"劃線月份" = "0"
"劃線模式" = "每周"
"啟動移停" = "100%"
"報價方式" = "每分鐘"
"多空進場相同" = "無"
"多進場" = "2%"
"夜盤停損" = "使用"
"夜盤提早結束" = "使用"
"夜盤直停" = "使用"
"夜盤移停" = "使用"
"夜盤結束時間" = "1600"
"夜盤進場" = "使用"
"夜盤運作" = "使用"
"子策略最多進場數" = "100"
"截止時送單" = "是"
"拉回進場" = "0.1%"
"掛單策略" = "直接送單"
"換倉日動作" = "換倉"
"最多等待時間" = "1440"
"最大單邊口數" = "50"
"最少進場點" = "0"
"最後劃線時間" = "1330"
"每N分鐘" = "15"
"產品" = "COMEX/SI"
"留倉超過x口連假不平倉" = "100"
"直接停利" = "4%"
"移停拉回" = "0.2%"
"空進場" = "100%"
"等待較佳價時間" = "1"
"網格間距" = "10"
"進場方式" = "固定一口"
"進場金額" = "1000"
"遇連假平倉" = "否"
"限價位置" = "0.1%"
"限價方式" = "限價價位"
"顯示未平倉" = "無"
