[strategy]
name = "fd04_時間沖"
project = "srp"
strategy_id = "fd04_時間沖"

[params]
"策略" = "fd04_時間沖"
"近月代碼" = "TX (台指期)"
"滑價" = "1.0"
"交易時間" = "08:45-13:44"
"契約價值" = "200.0"
"最小跳動點" = "1.0"
"最小跳動金額" = "200.0"
"開始日期" = "2012/01/04"
"結束日期" = "2025/10/31"
"發布日期" = "2025/07/04"

[params."策略參數"]
"ADF天期" = "20"
"D" = "20"
"M" = "1"
"N" = "1"
"S" = "1"
"X" = "1"
"extend_hour" = "否"
"fee" = "1"
"startDate" = "2012-01-01"
"停損" = "100%"
"停損修正" = "100%"
"出場時間" = "0900"
"前日美國休市日排除" = "排除"
"合約天數濾網" = "不論"
"均線濾網" = "無"
"多空" = "多"
"排名比天數" = "100"
"排名比最低" = "0"
"排名比最高" = "100"
"日內漲幅最大" = "100"
"日內漲幅最小" = "0"
"日內漲幅濾網" = "無"
"日曆中止" = "固定S日"
"日曆濾網" = "無"
"日曆起始" = "每星期N"
"最多持倉分鐘" = "1440"
"次日美國休市日排除" = "不論"
"現貨TR排名比" = "不論"
"產品" = "TW/TX"
"相對昨收" = "無"
"美國休市日排除" = "排除"
"臨時出場時間" = "2359"
"進場方式" = "固定一口"
"進場星期" = "0"
"進場時間" = "1330"
"進場盤勢" = "不論"
"進場金額" = "10000"
"遇連假排除" = "排除"
