[strategy]
name = "fd16_CoinbasePremium"
project = "srp"
strategy_id = "fd16_CoinbasePremium"

[params]
"策略" = "fd16_CoinbasePremium"
"近月代碼" = "BTCUSDT"
"滑價" = "0.1%"
"交易時間" = "00:00-23:59"
"契約價值" = "1.0"
"最小跳動點" = "0.01"
"最小跳動金額" = "0.01"
"開始日期" = "2017/08/17"
"結束日期" = "2025/11/02"
"發布日期" = "2025/05/30"

[params."策略參數"]
"M分鐘動能" = "0"
"N" = "45"
"fee" = "0.1%"
"startDate" = "2004-07-01"
"中線出場" = "無"
"交易週期" = "每小時"
"價差計算" = "分K開盤"
"價差貨幣兌" = "BTC"
"多空" = "皆可"
"正價差空" = "20"
"產品" = "Binance/BTCUSDT"
"逆價差多" = "5"
"進場方式" = "固定金額"
"進場次數上限" = "1"
"進場金額" = "1000"
"顯示未平倉" = "無"
